suurt8ll/open_webui_functions

- function_updater.py
> Enhancement: Function Sync Helper

- README.md
- dev.sh
- function_updater.py
Add `dev.sh` script that:
- builds the front-end if necessary
- updates pip dependencies
- launches tmux session with 2 windows: backend and `function_updater`.
> Enhancement: better development environment

- gemini_manifold.py
- pipe_function_template.py
- pipe_function_template_no_comments.py
- venice_manifold.py
> Enhancement(Gemini, Venice): use Open WebUI's files API for storing the images

- gemini_manifold.py
- pipe_function_template_no_comments.py
- venice_manifold.py
> Enhancement(general): better error handling

- gemini_manifold.py
- gemini_manifold_companion.py
- grounding_w_google_search.py
- test_and_example_functions/installing_other_plugins.py
Move some logic related to grounding with google search to a separate filter function. The pipe function will automatically install and enable the filter function for search supported models by fetching it from my repo and using backend methods.
Simplifies the gemini manifiold by making things more modular. Adds seamless integration with already existing web search button in the front-end, no seaparte `++SEARCH` model needed.
> feat: grounding search filter function

- gemini_manifold.py
> feat: search query status message

- gemini_manifold.py
- manifold_types.py
> feat: token usage

- gemini_manifold.py
- manifold_types.py
> fix(gemini): temporary chat missing chat_id

- gemini_manifold.py
Gemma models do not support system_instruction as well as Gemini 2.0 Image generation model.
Placed their handling along with Image generation, in case you make changes to pass the system prompt to the user message. NB! It would be great if this behavior could be controlled by the user valve.
- [+] Streaming response
- [+] LLM responds to user input.
- [+] LLM processes image inputs (history/prompt).
- [+] LLM generates images from prompts.
- [+] LLM uses search; citations displayed.
- [+] Non-streaming resposne
- [+] LLM responds to user input.
- [+] LLM processes image inputs (history/prompt).
- [+] LLM generates images from prompts.
- [+] LLM uses search; citations displayed.
- [+] Tests pass; code style consistent.
> Add Gemma support

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
Long story short, I decided to implement the Code execution tool support, as it's extremely handy even compared to my local Jupyter installation :) Please have a look.
- [+] Streaming response
- [+] LLM responds to user input.
- [+] LLM processes image inputs (history/prompt).
- [+] LLM generates images from prompts.
- [+] LLM uses search; citations displayed.
- [+] Non-streaming resposne
- [+] LLM responds to user input.
- [+] LLM processes image inputs (history/prompt).
- [+] LLM generates images from prompts.
- [+] LLM uses search; citations displayed.
- [+] Tests pass; code style consistent.
> Implement code execution functionality

- plugins/filters/system_prompt_injector.py
- plugins/pipes/gemini_manifold.py
- utils/manifold_types.py
If user disables the rich text input feature, then this is possible and better looking option.
> feat: collapsible prompt injector header

- plugins/pipes/gemini_manifold.py
some minor polishing after testing edge cases
> fix: polish code execution feature

- examples/associate_messages_to_files.py
- examples/citations.py
- plugins/filters/system_prompt_injector.py
- plugins/pipes/gemini_manifold.py
- plugins/pipes/venice_manifold.py
- requirements.txt
- utils/manifold_types.py
> perf: faster url resolution

- examples/fastapi_request.py
- examples/filter_template.py
- examples/pipe_template.py
- examples/status_messages.py
- examples/task_detection.py
- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
resolves #73, resolves #74, resolves #75
> fix: issues with model responses

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
- utils/manifold_types.py
> reafc(gemini): rework error handling in `Pipe.pipe`

- plugins/pipes/gemini_manifold.py
Add YouTube video input support by extracting the URL and passing it as a Part, per Google's documentation. 
https://ai.google.dev/gemini-api/docs/video-understanding#youtube
> Add: YouTube video input support

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
Ensure max compatibility with the new 2.5 flash model and some other general thinking model related improvements.
> feat(gemini): 2.5 flash

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
> chore(gemini): final touchups before 1.16.0 release

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
> feat(gemini): logging improvements

- plugins/pipes/gemini_manifold.py
make the spaghetti more readable
> refactor: better manifold method ordering

- plugins/filters/gemini_manifold_companion.py
Copy logging improvements I did in `gemini_manifold.py` into companion filter.
> feat(companion): improve logging

- plugins/pipes/venice_manifold.py
copy-pasted the improved logic from `gemini_manifold.py`
> feat(venice): better logging

- plugins/pipes/venice_manifold.py
> refactor(venice): better folds

- plugins/pipes/gemini_manifold.py
Addresses issue #78 
I'm not set up on Vertex so I can't test myself, but I figured I'd give us a head start.
> feat(gemini): add support for Google Cloud Vertex AI integration

- plugins/pipes/gemini_manifold.py
feat(gemini):  default all UserValves fields to None, meaning the values are taken from Valves if not given.
Makes this much more scalable thanks to `_get_merged_valves`. One key assumtion is that all `UserValves` fields are also in `Vavles` with exact same names.
> feat(gemini): better user valves logic

- plugins/pipes/gemini_manifold.py
Hardcoded models now get appended to Gemini Developer API models and each user has an option to choose between Vertex AI or Gemini Developer API.
> fix(gemini): make Vertex AI selection through `UserValves` work

- plugins/pipes/gemini_manifold.py
It sounds like you're describing a fix for how YouTube URLs are handled in your code!
Previously, it seems like when a YouTube link was mixed with other text, the order of things got a bit jumbled. This change makes sure that the text parts are created before and after the YouTube URL part, just like how you wrote it in the prompt.
So, if you wrote something like:
"Describe this video please:
https://www.youtube.com/watch?v=fC7oUOUEEi4
Include timestamps in your summary."
It will now be understood correctly with the text before the link, the link itself, and the text after the link.
I see you also mentioned that some existing tests are currently failing. It sounds like that's due to a separate issue with how those tests are set up, and not a problem with this specific change for YouTube …
> fix(gemini): slight correction to YouTube URL parsing

- plugins/pipes/gemini_manifold.py
Instead of hardcoding models for vertex, we do not filter on `supported_actions`, and use model.name when model.display_name is None. This could return too many models for locations other than global, but it's likely a better workaround.
> Simplify vertex ai model listing

- .github/scripts/generate_changelog.sh
- .github/scripts/parse_tag.sh
- .github/workflows/release.yml
Handle pre-releases better and detect contributors.
> ci: better release workflow

- plugins/pipes/gemini_manifold.py
> fix(gemini): Vertex AI does not support URL context.

- plugins/filters/gemini_manifold_companion.py
> fix(companion): make Gemini Manifold Companion work with new thoughts feature

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
Add gemini-2.5-pro-preview-06-05 model code where appropriate.
> fix(gemini): Add gemini-2.5-pro-preview-06-05 model code

- examples/pipe_template.py
- examples/pipe_template_verbose.py
did a deepdive into Open WebUI's backend and frontend code. useful for giving additional context to LLM's when working with these functions.
> docs(webui): better documentation for pipe function

- plugins/pipes/gemini_manifold.py
- requirements.txt
closes #102
This provides nice abstraction for Google Files API related operations. It will be later used for any possible file that get's sent to the API (images, video, audio, documents, text files etc.)
https://github.com/suurt8ll/open_webui_functions/blob/a45ac8c32d98453c5ee5206332e6077e4fa76f34/plugins/pipes/gemini_manifold.py#L112-L123
> feat(gemini): Google Files API Abstraction Layer

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
Added new Gemini 2.5 Flash Lite model endpoint where appropriate!
> feat: Add Gemini 2.5 Flash Lite

- plugins/pipes/gemini_manifold.py
- requirements.txt
- tests/test_gemini_manifold.py
I rebased my fork that I use at work to connect to Vertex AI. It solves a minor bug, adds URL context to Vertex AI and allows the user to use files stored on the GCS. Feel free to use any of the commits or decline the PR altogether.
> Feature: GCS, URL Context and minor improvements focused on Vertex AI.

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
- requirements.txt
hopefully does something to #182
> chore(gemini): bump `google-genai` to `1.29.0`

- plugins/pipes/gemini_manifold.py
> fix(gemini): exclude non-thinking 2.5 models

- plugins/pipes/gemini_manifold.py
This PR adds streaming Nano Banana (aka Gemini 2.5 Flash Image Preview, sheesh) model support.
Fixes #189
> Add Nano Banana support

- plugins/pipes/gemini_manifold.py
Made the Genai response -> OWUI return object processing more modular. Non-streaming responses now support reasoning, code execution and most importantly native image gen. outputs. closes #189
> feat(gemini): rewrite response handling

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
Added ```gemini-flash-latest```, ```gemini-2.5-flash-preview-09-2025```, ```gemini-flash-lite-latest```, and ```gemini-2.5-flash-lite-preview-09-2025``` where appropriate!
> feat(gemini): Add ```gemini-flash-latest```, ```gemini-flash-lite-latest``` model codes and aliases

- plugins/filters/gemini_manifold_companion.py
- plugins/pipes/gemini_manifold.py
Added ```gemini-2.5-flash-image``` model code where appropriate. Refactored the ```"IMAGE"``` ```response_modalities``` into a list for easier maintenance.
> feat(gemini): Add ```gemini-2.5-flash-image```, refactor response_modalities handling
